### ISSUE TITLE
HashDiff dependency causing trouble with webmock 3.6

### ISSUE THREAD

**Issue by mikz** [kontena/k8s-client#137]
```
Bundler could not find compatible versions for gem "hashdiff":
  In Gemfile:
    k8s-client (>= 0.10) was resolved to 0.10.1, which depends on
      hashdiff (~> 0.3.7)

    webmock (~> 3.6) was resolved to 3.6.0, which depends on
      hashdiff (< 2.0.0, >= 0.4.0)
```

Hashdiff recently released a new version that changes the constant name due to some name clash with other gem (https://github.com/liufengyun/hashdiff/pull/65)

**Comment by kke** [comment]
Updating now would require hashdiff 1.0 beta, otherwise you get a warning every time hashdiff is loaded. Waiting for 1.0.

**Comment by mikz** [comment]
Why you can't use the correct constant like webmock does with 0.4.0 ?

**Comment by kke** [comment]
It seems to warn on `require`, not when used.
