### ISSUE TITLE
Excon 0.62.0 issue

### ISSUE THREAD

**Issue by bgeesaman** [kontena/k8s-client#138]
Hi!  Thanks for this lovely gem.  It's the backbone of https://github.com/bgeesaman/inspec-k8s (the train-kubernetes plugin, specifically).  I noticed when installing excon from other gems, it installs `0.64.0`.  When I install `k8s-client`, it pulls in `0.62.0`.  When using inspec, this can lead to both `0.62.0` and `0.64.0` installed and then they conflict when running inspec.

Would you consider changing the gem dependency to `>= 0.62.0` and making a new versioned release?

Thanks!

**Comment by kke** [comment]
Sure. Optimally I would like to have the dependency dropped and replaced with plain net-http. Having dependencies in client libs is often a problem.

**Comment by kke** [comment]
https://rubygems.org/gems/k8s-client/versions/0.10.2
