### ISSUE TITLE
Executable bin/k8s-client should be dropped

### ISSUE THREAD

**Issue by kke** [kontena/k8s-client#141]
I have no idea if it is still up to date, probably not.

**Comment by jakolehm** [comment]
I have never used it really.

**Comment by jnummelin** [comment]
Probably not really up-to-date. But we do need to have some examples how the client is actually used in different cases. So maybe not just completely drop it, maybe "refactor" it to a set of (executable?) individual examples

**Comment by jakolehm** [comment]
> Probably not really up-to-date. But we do need to have some examples how the client is actually used in different cases. So maybe not just completely drop it, maybe "refactor" it to a set of (executable?) individual examples

Yes, refactor to examples would be perfect.
