### ISSUE TITLE
`watch` as in the example, lines printed on shutdown instead of as events happen 

### ISSUE THREAD

**Issue by vitobotta** [kontena/k8s-client#168]
Hi! I am trying to write a stupid simple controller that needs to watch for when Velero backups start and complete and send a slack notification. I am using the example in the readme, but the lines with the event details are printed altogether when I shutdown the script, instead of being printed as the events happen. Any idea of why? Thanks!

**Comment by vitobotta** [comment]
So it looks like the watching is working but I have to add `STDOUT.flush` after `puts` otherwise it doesn't show anything until I shutdown the script. Why is that? :)

**Comment by jakolehm** [comment]
> So it looks like the watching is working but I have to add `STDOUT.flush` after `puts` otherwise it doesn't show anything until I shutdown the script. Why is that? :)

You are probably missing `$stdout.sync = true`.

**Comment by vitobotta** [comment]
Yeah that works too. Closing this one.
