### ISSUE TITLE
GKE support

### ISSUE THREAD

**Issue by matti** [kontena/k8s-client#47]
GKE kubeconfig has calls to gcloud CLI. And token is somehow mangled inside a service account.

So either implement GKE support or have documentation on how to get the required token and steps.

**Comment by nevalla** [comment]
Kubeclient gem instructs people this way: https://github.com/abonas/kubeclient#googles-application-default-credentials. So based on that, something like this might work:

```ruby
require 'googleauth'
def token
  scopes = ['https://www.googleapis.com/auth/cloud-platform']
  authorization = Google::Auth.get_application_default(scopes)
  authorization.apply({})
  authorization.access_token
end

K8s::Client.config(K8s::Config.load_file('~/.kube/config'),
  auth_token: token
)
```

**Comment by matti** [comment]
Thanks, I'll try

**Comment by matti** [comment]
So that solves the first part of this, but I have no idea how to `gcloud container clusters get-credentials asdf` to get the actual credentials to the cluster -- maybe with https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-container but I already went with gcloud/kubectl & popen3.

**Comment by matti** [comment]
and that gem provides no (?) way to export the credentials in a way that would work with `k8s-client`

**Comment by jakolehm** [comment]
Fixed in #52

**Comment by matti** [comment]
https://github.com/kontena/mortar/issues/71#issuecomment-434034921

@jakolehm reopen?

**Comment by jakolehm** [comment]
I think we need a new issue, https://github.com/kontena/mortar/issues/71#issuecomment-434034921 is not GKE specific.

**Comment by matti** [comment]
whatever, it still does not work in GKE
