### ISSUE TITLE
Override current-context in K8s::Client.config

### ISSUE THREAD

**Issue by d11wtq** [kontena/k8s-client#48]
According to the documentation, `current-context` is one of the supported overrides. I can't seem to get this to work. Have tried various ways of specifying it. What's the correct way to do this?

``` ruby
K8s::Client.config(
  K8s::Config.load_file(config_path),
  :'current-context' => 'minikube'
)
```

When I have the `current-context` set to `production` in my shell, this override does not seem to take effect.

**Comment by jnummelin** [comment]
There's no way to override the context at the `K8s::Client.config` level. What you could do instead, is to load the config bit differently:
```
cfg_hash = YAML.load_file('/Users/jussi/.kube/config')
cfg_hash['current-context'] = 'foo'
client = K8s::Client.config(K8s::Config.new(cfg_hash))
```
The reason being that the at the client level we do not have any info on context etc. config concepts, and neither we should IMO.

**Comment by d11wtq** [comment]
Awesome, thanks @jnummelin!

**Comment by tadman** [comment]
Having this as a feature would help a lot with multi-context situations.
