### ISSUE TITLE
Allow to use Telepresence mounted volumes with in_cluster_config

### ISSUE THREAD

**Issue by nevalla** [kontena/k8s-client#86]
Telepresence mounts service account's token and ca cert in `$TELEPRESENCE_ROOT/var/run/secrets/kubernetes.io/serviceaccount/` path. Would be nice if we could allow to use this files with `in_cluster_config` method.

**Comment by kke** [comment]
It's possible to pass the ssl_ca_path and auth token manually, but it could still try to use the TELEPRESENCE_ROOT when set.

**Comment by kke** [comment]
Looks like not via `K8s::Client.in_cluster_config` which does not pass the `**options`.
